version: '2'

services:
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guac
  guacd:
    image: guacamole/guacd:0.9.14
    restart: always
    networks:
      - guac
    ports:
      - "4822:4822"
  guac:
    image: guacamole/guacamole:0.9.14
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./openid:/opt/guacamole/openid/
      - ./config/start.sh:/opt/guacamole/bin/start.sh
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
      
      GUACAMOLE_HOSTNAME: http://localhost:8080/guacamole/#
      KEYCLOAK_HOSTNAME: keycloak_hostname
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT: guacamole
      OPENID_CLAIM_TYPE: preferred_username
      OPENID_SCOPE: openid profile
      OPENID_ALLOWED_CLOCK_SKEW: 99999
      OPENID_MAX_TOKEN_VALIDITY: 300
      OPENID_MAX_NONCE_VALIDITY: 10
    networks:
      - guac
    depends_on:
      - postgres
      - guacd
    links:
      - postgres
      - guacd

volumes:
  data:
    driver: local

networks:
  guac:
    driver: bridge
