version: '3.3'

services:
  postgres:
    image: postgres:9.6.11
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
  guacd:
    image: guacamole/guacd:0.9.14
    restart: always
    ports:
      - "4822:4822"
  guac:
    image: guacamole/guacamole:0.9.14
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd
